services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html:cached
    environment:
      - APP_ENV=prod
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - teach-r-network
      - shared-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=prod
    # command: ["npm", "start"]
    ports:
      - "3001:3001"
    networks:
      - teach-r-network
      - shared-network

  fpm:
    build:
      context: ./backend/docker
      dockerfile: Dockerfile-php
    environment: 
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9001:9001"
    depends_on:
      - backend 
    networks:
      - teach-r-network
      - shared-network

networks:
  teach-r-network:
    driver: bridge
  shared-network:
    external: true
    name: shared-network