services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html:cached
      - ./backend/vendor:/var/www/html/vendor:delegated
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root:@db:3306/teachR
    networks:
      - teachR-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    networks:
      - teachR-network

  nginx:
    build:
      context: ./backend/docker
      dockerfile: Dockerfile-nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html:cached
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
      - fpm
    networks:
      - teachR-network

  fpm:
    build:
      context: ./backend/docker
      dockerfile: Dockerfile-php
    environment: 
      - DATABASE_URL=mysql://root:@db:3306/teachR
    volumes:
      - ./backend:/var/www/html
    networks:
      - teachR-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      # - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=teachR
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - teachR-network

volumes:
  mysql_data:

networks:
  teachR-network:
    driver: bridge